// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolityczneSpektrum.Data;

namespace PolityczneSpektrum.Migrations
{
    [DbContext(typeof(PolityczneSpektrumDbContext))]
    [Migration("20190107222326_start")]
    partial class start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PolityczneSpektrum.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Answer");

                    b.Property<string>("Content");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("PolityczneSpektrum.Models.QuestionEditModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Answer");

                    b.Property<string>("Content");

                    b.HasKey("Id");

                    b.ToTable("QuestionwithAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
